name: switch-release

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean
      draft_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

jobs:

  build-switch-release:
    runs-on: ubuntu-22.04
    container: devkitpro/devkita64:latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install git build-essential cmake zip libsdl2-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-nouveau2

      - name: Build postal-nx
        run: |
          cd $GITHUB_WORKSPACE
          make
          mv bin/postal.nro $GITHUB_WORKSPACE

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Postal-NX ${{ github.run_number }}
          path: postal.nro

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          DRAFT: ${{ inputs.create_release }}
        with:
          name: Postal-NX ${{ github.run_number }}
          files: postal.nro
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: ${{ env.DRAFT }}
          make_latest: true
          