name: switch-release

on:
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean
      draft_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
      game_version:
        description: "The version of Postal-NX"
        default: "1.0.2"
        required: true
        type: string

jobs:

  build-switch-release:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install git build-essential cmake zip libsdl2-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-nouveau2

      - name: Build Postal-NX
        run: |
          cd $GITHUB_WORKSPACE
          make
          mv bin/postal.nro $GITHUB_WORKSPACE

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.4.3
        env:
          GAME_VERSION: ${{ inputs.game_version }}
        with:
          name: Postal-NX ${{ env.GAME_VERSION }}-${{ github.run_number }}
          path: postal.nro

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          DRAFT: ${{ inputs.create_release }}
          GAME_VERSION: ${{ inputs.game_version }}
        with:
          tag_name: ${{ env.GAME_VERSION }}-${{ github.run_number }}
          name: Postal-NX ${{ env.GAME_VERSION }}-${{ github.run_number }}
          files: postal.nro
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: ${{ env.DRAFT }}

          
